name: scp files
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Decrypt secret
      run: ./.github/scripts/decrypt.sh
      env:
        LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
    - uses: actions/checkout@master
    - name: send files over the network
      run: ./.github/scripts/scp.sh
      env:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        source: "./a.js"
        target: "/home/ubuntu/temp"