name: scp files
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: webfactory/ssh-agent@v.0.2.0
        with:
          ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}
      - uses: actions/checkout@master
      - name: Decrypt secret
        run: ./.github/scripts/decrypt.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
      - uses: actions/checkout@master
      - name: send files over the network
        run: echo "running..." && cat ~/.ssh/known_hosts && ./.github/scripts/scp.sh
        env:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          source: './a.js'
          target: '/home/ubuntu/temp'
