name: scp files
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}
      - uses: actions/checkout@master
      - uses: obbap1/quick-scp@master
      - name: send files over the network
        run: ./.github/scripts/scp.sh
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          SOURCE: './a.js'
          TARGET: '/home/ubuntu/temp'
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
