name: scp files
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get name of GPG file
        run: |
          nameOfGpg=`echo *.gpg | awk '{print $1}'`
          echo "${nameofGpg}, file has been found"
          filename="${nameOfGpg%.*}"
          pemFileName="${filename#**.}"
        id: gpg
      - name: Run SSH Agent
      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}
      - name: Run SCP command
      - uses: obbap1/quick-scp@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          SOURCE: './a.js'
          TARGET: '/home/ubuntu/temp'
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
          NAME_OF_GPG: ${{steps.gpg.nameOfGpg}}
          PEM_FILE_NAME: ${{steps.gpg.pemFileName}}
